- trainers: Trainer Trainerson
  url: https://example.com/training
  title: Title of training
  length: 3
- trainers: Trainer Trainerson
  url: https://example.com/training
  title: Title of training
  length: 3
- trainers: Trainer Trainerson
  url: https://example.com/training
  title: Title of training
  length: 3
- trainers: Trainer Trainerson
  url: https://example.com/training
  title: Title of training
  length: 3
- trainers: Trainer Trainerson
  url: https://example.com/training
  title: Title of training
  length: 3
- trainers: Trainer Trainerson
  url: https://example.com/training
  title: Title of training
  length: 2
- trainers: Trainer Trainerson
  url: https://example.com/training
  title: Title of training
  length: 2
- trainers: Trainer Trainerson
  url: https://example.com/training
  title: Title of training
  length: 2
- trainers: Trainer Trainerson
  url: https://example.com/training
  title: Title of training
  length: 2
